### ISSUE TITLE
Problems joining WiFi networks

### ISSUE THREAD

**Issue by gaumarjos** [Bostwickenator/STGUploader#10]
I installed the STG Uploader app on my Sony a6000 camera with the pmca-gui. Just that, nothing else. For some reason I cannot connect it to my WPA2 protected home WiFi network: the app asks for my password but after I click ok, it gives an error "Cannot find the access point", but it's there and it's able to see it in the list.

**Comment by Deph0** [comment]
Hi, this is beyond the scope of this application, if you are having trouble regarding the wifi, please see your camera manual for reference.

However, i suggest you try another WIFI network, for example your phone's hotspot functionality.

**Comment by Bostwickenator** [comment]
WiFi management is done at the OS level.
