### ISSUE TITLE
Can't Log in on camera And Trying to configure using C.DAT

### ISSUE THREAD

**Issue by R3verseCha0s** [Bostwickenator/STGUploader#13]
So I have a HX-400V and I have installed the app but i can't click on textboxes to put my email or pass. And after a while I found a file in my SD Card called `"C.DAT"` in the following directory `"D:\PRIVATE\STG`". I opened this file on Notepad++ and found this line `"{"credentials":{}}"` and I was wondering if I could put my credentials there. If yes tell me in what form should I enter them. Could it be something like this "`{"credentials":{"example@gmail.com", "password"}}"`. Please tell me the correct syntax, just to see if it will work. Thanks, Keep up the good work.

P.S if you need more info let me know by contacting me on mixalisselgall@gmail.com , or Reply here.

**Comment by Deph0** [comment]
You need to obtain the OAuth from google, either by using the app on the camera to log on with on-screen keyboard, or follow the instruction on the website, [here](https://www.stg-uploader.xyz/auth.html).

**Comment by Bostwickenator** [comment]
@Deph0 thanks that is completely correct
