### ISSUE TITLE
Migrate to the NEW GOOGLE PHOTOS API (woooo!)

### ISSUE THREAD

**Issue by Bostwickenator** [Bostwickenator/STGUploader#14]
Google has given us a Google Photos API after only what 4 years. We should use this instead.

**Comment by Deph0** [comment]
Woo! It even supports creating albums, so no more worries about duplicated filenames!
[Google Photo API Page](https://developers.google.com/photos/) for the curious!

**Comment by Bostwickenator** [comment]
Due date March 2019
