### ISSUE TITLE
App is broken--needs to be updated to Google Photos API

### ISSUE THREAD

**Issue by dlxmax** [Bostwickenator/STGUploader#19]
March 15th has passed, so the workaround for continuing to use the Picasa API has ceased, and photos are no longer able to be uploaded.

I love this app and sincerely hope it's an easy process to convert it over to the Google Photos API. Thanks so much for your efforts.

**Comment by inakihn** [comment]
+1. Love the app. I have no idea how you go about developing the app or how to build, test, etc, never developed for android, but if there's anything I can help with, ping me. Thanks for the effort.

**Comment by Bostwickenator** [comment]
Just about ready guys. Should be able to use it soon but there will be BIG SCARY warnings until Google signs off on me using that API

**Comment by Bostwickenator** [comment]
Complete in v1.7, please generate new credentials files to use.

**Comment by retrography** [comment]
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

This is what I get from Google when trying to sign in.

**Comment by derouck** [comment]
I get this error as well, is there a workaround for this already? :-)
