### ISSUE TITLE
License

### ISSUE THREAD

**Issue by schnatterer** [Bostwickenator/STGUploader#20]
Could you please add a license to your code, such as the MIT license?
Otherwise it's difficult to reuse your code, which I would like to do.

**Comment by Bostwickenator** [comment]
Done, happy hacking

**Comment by schnatterer** [comment]
I reused your FilesystemScanner in [pmcaFilesystemServer](https://github.com/schnatterer/pmcaFilesystemServer).
Thanks for sharing!
