### ISSUE TITLE
Sign in with Google temporarily disabled

### ISSUE THREAD

**Issue by derouck** [Bostwickenator/STGUploader#23]
When I try to create the auth token, it seems it's disabled for now. Any chance this will get enabled again :-) Would love to try this application! 👍 

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

http://stg-uploader.s3-website-us-east-1.amazonaws.com/auth.html

**Comment by deepfriedmind** [comment]
The Malwarebytes Chrome extension is also blocking access to https://www.stg-uploader.xyz/. See [screenshot](https://i.imgur.com/VYSBBPZ.png). Has it been compromised?

**Comment by Bostwickenator** [comment]
Nope

**Comment by Bostwickenator** [comment]
An update on the auth issues. Google are now asking me to email them a video demoing how the app works for their mod team.

**Comment by Bostwickenator** [comment]
Approved after a couple of rounds. Yay!

**Comment by deepfriedmind** [comment]
Thanks for resolving the Google auth issues! Do you have any idea as to why the Malwarebytes Chrome extension would completely block `https://www.stg-uploader.xyz/`? I haven't seen it block anything 100% legit before.

**Comment by Bostwickenator** [comment]
It might have picked up on signal flags from Google Auth freaking out. It's
all signed using Amazon certs distributed through S3 and CloudFront so it's
definitely secured. There is some slightly weird code in there where I
build the credentials file and direct the browser to download it that's
definitely a bit abnormal. But really I'm not sure what heuristic tripped
it.
