### ISSUE TITLE
"Could not validate certificate" 

### ISSUE THREAD

**Issue by ethulin** [Bostwickenator/STGUploader#25]
Hello!

I installed the app, authorized it via the web link, and loaded the C.DAT file into the STG directory.

When I launch the app, I am asked to log in to my wifi. I do that, but am not prompted to grant an oAuth token as described in the instructions. The log file is posted below. It appears that it "Could not validate certificate". Not sure what to do next?

[INFO] setting wifi enabled state to true
[INFO] starting wifi settings activity
[INFO] setting wifi enabled state to true
[INFO] Resume org.bostwickenator.googlephotos.LoginActivity
[ERROR] javax.net.ssl.SSLHandshakeException: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: current time: Fri Jan 16 20:35:10 GMT+00:00 2015, validation time: Fri Jun 19 00:00:42 GMT+00:00 2020
[INFO] Pause org.bostwickenator.googlephotos.LoginActivity

**Comment by Bostwickenator** [comment]
I think the issue is in your error message. Your camera time is set to 2015 which is before the validity period of the security credentials. Try adjusting the cameras date and time.

**Comment by ethulin** [comment]
Well that's embarrasing. Almost like I should read the whole error message before posting.

Thanks, resolved.

**Comment by Bostwickenator** [comment]
No worries at all! I'd be lying if I said I hadn't done the same thing a dozen times.
