### ISSUE TITLE
[ERROR] java.io.FileNotFoundException: https://picasaweb.google.com/data/feed/api/user/default/albumid/default

### ISSUE THREAD

**Issue by Bostwickenator** [Bostwickenator/STGUploader#5]
Hi,

First of all, sorry to post this issue here , in the wrong project because it is about STG Uploader, but I couldn't find a better place to contact you. Second: I would love to help fix this bug and make this app even better. I have tons of experience with Android app development.

So when do I get the error:
Since it happened, it happens every time I try to upload again. So now uploading never works (anymore). It worked the first few times, but at a certain point it stopped working. This is what I see/do:

start app
see it connecting to wifi
see the user interface with the two buttons Start Upload and Settings. I also see that 100 photos are ready to upload.
When I click Start Upload it tries to start upload, and I see the 'small animation', but it does not upload and after a while it just stops.
The logs says:
[INFO] setting wifi enabled state to true
[INFO] Resume org.bostwickenator.googlephotos.LoginActivity
[INFO] Pause org.bostwickenator.googlephotos.LoginActivity
[INFO] Resume org.bostwickenator.googlephotos.MainActivity
[INFO] Response Code : 403
[ERROR] java.io.FileNotFoundException: https://picasaweb.google.com/data/feed/api/user/default/albumid/default
[INFO] Response Code : 403
[ERROR] java.io.FileNotFoundException: https://picasaweb.google.com/data/feed/api/user/default/albumid/default
[INFO] Response Code : 403

What doesn't work:

Clearing the database
Re authorizing Google
What does work (strangely enough):

Installing the app again (without removing it first)

**Comment by nevixa** [comment]
Hi,

Thanks for sharing the code. I'm able to build the apk and install the app on my camera, but it gives me an error with login into Google. I tried removing the C.DAT file, but I get a 401 error on the login screen and saying it is missing oauth. I'm not sure if I'm missing some files/libraries or if I'm just doing something wrong. Maybe you can help me out?

Thanks

**Comment by Bostwickenator** [comment]
There are no keys shared in the repo. Check the AuthenticationManager class https://github.com/Bostwickenator/STGUploader/blob/6328fccea73fb2e3881cf58fb6cdb499aa12f1e4/app/src/main/java/org/bostwickenator/googlephotos/AuthenticationManager.java#L29-L30. If you want to build a functioning version you will need to register your own application with Google. I will add this to the readme.

**Comment by brianc118** [comment]
@Bostwickenator When you register the application with google, which apis did you choose and what application type did you choose? Also I notice that Android apps to not have a client secret. Did you choose Web Application or Other?
<img width="215" alt="screen shot 2017-05-18 at 11 14 56 pm" src="https://cloud.githubusercontent.com/assets/4782836/26203767/d9907a18-3c1f-11e7-939e-43ecdeefdff5.png">

**Comment by Bostwickenator** [comment]
Yes choose web. The Android type relies on Google Play Services which we
don't have on the camera.

**Comment by zoltanf** [comment]
Hello. Thanks for this project. Any update on this issue?

**Comment by Bostwickenator** [comment]
Doesn't happen for me you might be exceeding some kind of API limit. How many photos are you uploading?

**Comment by zoltanf** [comment]
I can't seem to repeat it now. It was around 200 fotos last time it happened.
