### ISSUE TITLE
Skip the ARW files?

### ISSUE THREAD

**Issue by windyweather** [Bostwickenator/STGUploader#6]
Kudos. Even works on my old out of date NEX-6 camera.
I had a little trouble figuring out how to put in the WPA password, but that's not your problem. When I tried to connect to the other WiFi that I have I could put in the pw without issue.

But I take photos with JPG + ARW and can't see a way to skip uploading the ARW to google. Takes too long doing both, obviously. Just a checkbox to skip those would be nice.
Thanks again.
ww

**Comment by Bostwickenator** [comment]
Done in 1.4
