### ISSUE TITLE
Clarification about logging in with onscreen keyboard

### ISSUE THREAD

**Issue by alza-bitz** [Bostwickenator/STGUploader#7]
The STG webpage states _"Logging in on your camera can be very hard with an onscreen keyboard."_ 

I am not finding it hard, but impossible! I have an RX100 Mk III camera, and I can't find any way to show an onscreen keyboard at all. What am I doing wrong, or does this model not have an onscreen keyboard?

Thanks 🙂

**Comment by Bostwickenator** [comment]
Unfortunately I don't know. Each camera has a custom build of Android on it and it's hard to predict this. Web login should solve this for you though.
