### ISSUE TITLE
The auth webpage method of logging in doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by alza-bitz** [Bostwickenator/STGUploader#9]
Just in case no-one already reported this yet..

With Edge, there is no prompt to download the `C.DAT` file, I just get redirected back to the auth page.

This is with Edge 41.16299.15.0 on Windows 10 1709, 16299.64

**Comment by Bostwickenator** [comment]
Thanks for that! I'll add instructions to use Chrome for now
